version: '3.5'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
    container_name: postgres
    # volumes:
    # - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - efx-backend-network

  admin:
    image: adminer
    restart: always
    networks:
      - efx-backend-network
    depends_on:
      - db
    ports:
      - 8080:8080

  backend:
    image: oven/bun:latest
    working_dir: /code
    command: bun dev
    volumes:
      - ./:/code:cached
    environment:
      - NODE_ENV=development
      - APP_ENV=development
    ports:
      - '8888:8888'
    depends_on:
      - db
    networks:
      - efx-backend-network

networks:
  efx-backend-network:
    external: true
    driver: bridge
